### ISSUE TITLE
py3 compatibility - iteritems

### ISSUE THREAD

**Issue by ChaoticMind** [fabric/patchwork#23]
The usage of [`iteritems()`](https://github.com/fabric/patchwork/blob/cd0262879502cce331d3ece1091661b36a545419/patchwork/info.py#L30) is not py3 compatible.

Can't currently use the `package()` directive in `fabric2` tasks on python3.

**Comment by bitprophet** [comment]
Thanks for the catch!

**Comment by bitprophet** [comment]
Also of note, `package()` is pretty weak at the moment (it and the related `info` module were set up to work on various Linux distro families, _but_ only the CentOS backend was truly implemented) so...bear that in mind.

**Comment by bitprophet** [comment]
I'll put out a release soon with this in it, but note the caveat above. I'll probably pop out a feature release a bit later that does the bare minimum to make these modules a bit more fleshed out so they match the docstrings... 🤦‍♂️
